In [1]:
import torch

In [2]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)

In [5]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [12]:
sum_A = A.sum(axis=1, keepdim=True)
sum_A

tensor([[ 3.],
        [12.]])

In [13]:
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [17]:
X = torch.rand(size=(2, 3, 4))
X.shape

torch.Size([2, 3, 4])

In [20]:
len(X[0])

3

In [21]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [25]:
A_sum = A.sum(axis=1)
A_sum

tensor([ 3., 12.])

In [26]:
A / A_sum

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [28]:
X.shape

torch.Size([2, 3, 4])

In [29]:
X.sum(axis=0).shape

torch.Size([3, 4])

In [30]:
X.sum(axis=1).shape

torch.Size([2, 4])

In [31]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [32]:
torch.linalg.norm(A)

tensor(7.4162)

In [34]:
X.shape

torch.Size([2, 3, 4])

In [35]:
torch.linalg.norm(X)

tensor(3.0380)

In [42]:
torch.linalg.norm(X.flatten())

tensor(3.0380)

In [54]:
A = torch.randn(10000, 10000)

In [55]:
B = torch.randn(10000, 8000)
C = torch.randn(8000, 10000)

In [57]:
A @ C.T

tensor([[  24.1695, -184.9315,   13.9925,  ...,   30.8900,  -15.8153,
           81.4224],
        [ -35.2005,   15.1325,  -64.5527,  ...,  198.8661,   46.0153,
          -50.5955],
        [ 106.4686,  -19.1219,  119.6214,  ...,  -36.9038,   -1.1462,
          -74.2962],
        ...,
        [-188.8161,  -85.0900,   57.6463,  ...,  140.1173, -141.6408,
           40.2230],
        [ 110.9021,  -23.5648, -204.4281,  ...,  -92.4266,    9.1672,
         -156.7163],
        [-112.9633,   84.4827,   14.2142,  ...,  -86.8497, -213.6073,
           89.5653]])

In [60]:
A = torch.rand(size=(100, 200))
B = torch.rand(size=(100, 200))
C = torch.rand(size=(100, 200))

In [63]:
tensor = torch.stack([A, B, C])
tensor.shape

torch.Size([3, 100, 200])