In [1]:
import torch
from torch import nn
from torch.nn import functional as F

In [2]:
x = torch.arange(5)
torch.save(x, "x-file")

In [3]:
x2 = torch.load("x-file")
x2

tensor([0, 1, 2, 3, 4])

In [4]:
y = torch.zeros((4, 4))
torch.save([x, y], "x-files")

In [5]:
x2, y2 = torch.load('x-files')
x2, y2

(tensor([0, 1, 2, 3, 4]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]))

In [6]:
mydict = {'x': x, 'y': y}
torch.save(mydict, 'mydict')
mydict2 = torch.load('mydict')
mydict2

{'x': tensor([0, 1, 2, 3, 4]),
 'y': tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]])}

In [7]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.LazyLinear(256)
        self.output = nn.LazyLinear(10)

    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))

net = MLP()
X = torch.randn(size=(2, 20))
Y = net(X)

In [8]:
net.state_dict()

OrderedDict([('hidden.weight',
              tensor([[ 0.1876, -0.1921, -0.1587,  ...,  0.1955,  0.1670, -0.0005],
                      [ 0.1346,  0.0992,  0.2123,  ...,  0.2234, -0.2018,  0.0415],
                      [ 0.0576, -0.0227, -0.0413,  ...,  0.2058,  0.1628,  0.1089],
                      ...,
                      [-0.0316, -0.1540, -0.1011,  ...,  0.1275,  0.1285, -0.1605],
                      [-0.0706, -0.1536,  0.1652,  ..., -0.1691,  0.1904,  0.0955],
                      [-0.1444, -0.0972,  0.2119,  ..., -0.1653, -0.2035, -0.0326]])),
             ('hidden.bias',
              tensor([ 0.1483, -0.1025,  0.1192, -0.1706, -0.2036, -0.1000,  0.0771, -0.1983,
                      -0.1399, -0.1154,  0.1229,  0.2124,  0.0034, -0.0513,  0.1180, -0.2014,
                      -0.0758, -0.2149, -0.1999,  0.1093,  0.1581,  0.0059, -0.1684,  0.0581,
                       0.0692,  0.0646, -0.1540,  0.2097, -0.0269,  0.0713, -0.1526, -0.0052,
                      -0.2119,

In [9]:
torch.save(net.state_dict(), "mlp.params")

In [11]:
clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))

clone.eval()

MLP(
  (hidden): LazyLinear(in_features=0, out_features=256, bias=True)
  (output): LazyLinear(in_features=0, out_features=10, bias=True)
)

In [12]:
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])