In [1]:
import torch
from torch import nn

In [2]:
net = nn.Sequential(
  nn.LazyLinear(8),
  nn.ReLU(),
  nn.LazyLinear(1)
)

X = torch.rand(size=(2, 4))
net(X).shape

torch.Size([2, 1])

In [3]:
def init_normal(module):
  if type(module) == nn.Linear:
    nn.init.normal_(module.weight, mean=0, std=0.01)
    nn.init.zeros_(module.bias)

net.apply(init_normal)
net[0].weight.data[0], net[0].bias.data

(tensor([-0.0185,  0.0045, -0.0107, -0.0056]),
 tensor([0., 0., 0., 0., 0., 0., 0., 0.]))

In [4]:
def init_constant(module):
  if type(module) == nn.Linear:
    nn.init.constant_(module.weight, 1)
    nn.init.zeros_(module.bias)
    
net.apply(init_constant)
net[0].weight.data[0], net[0].bias.data[0]

(tensor([1., 1., 1., 1.]), tensor(0.))

In [6]:
def init_xavier(module):
  if type(module) == nn.Linear:
    nn.init.xavier_uniform_(module.weight)
    
def init_42(module):
  if type(module) == nn.Linear:
    nn.init.constant_(module.weight, 42)
    
net[0].apply(init_xavier)
net[2].apply(init_42)

print(net[0].weight.data[0])
print(net[2].weight.data)

tensor([ 0.1068, -0.5365,  0.2085,  0.5892])
tensor([[42., 42., 42., 42., 42., 42., 42., 42.]])


In [7]:
def my_init(module):
    if type(module) == nn.Linear:
        print("Init", *[(name, param.shape)
                        for name, param in module.named_parameters()][0])
        nn.init.uniform_(module.weight, -10, 10)
        module.weight.data *= module.weight.data.abs() >= 5

net.apply(my_init)
net[0].weight[:2]

Init weight torch.Size([8, 4])
Init weight torch.Size([1, 8])


tensor([[ 0.0000, -7.6826, -0.0000, -0.0000],
        [-0.0000, -5.7938, -0.0000, -7.8551]], grad_fn=<SliceBackward0>)

In [8]:
net[0].weight.data[:] += 1
net[0].weight.data[0, 0] = 42
net[0].weight.data[0]

tensor([42.0000, -6.6826,  1.0000,  1.0000])